In [2]:
import torch
from torch.nn import functional as F

In [6]:
for i in range(10):
    input_tensor = torch.ones(10)
    input_tensor *= i
    input_tensor[1:] *= -1
    print(input_tensor)
    print(F.cross_entropy(input_tensor, torch.tensor(0)))

tensor([0., -0., -0., -0., -0., -0., -0., -0., -0., -0.])
tensor(2.3026)
tensor([ 1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])
tensor(0.7966)
tensor([ 2., -2., -2., -2., -2., -2., -2., -2., -2., -2.])
tensor(0.1526)
tensor([ 3., -3., -3., -3., -3., -3., -3., -3., -3., -3.])
tensor(0.0221)
tensor([ 4., -4., -4., -4., -4., -4., -4., -4., -4., -4.])
tensor(0.0030)
tensor([ 5., -5., -5., -5., -5., -5., -5., -5., -5., -5.])
tensor(0.0004)
tensor([ 6., -6., -6., -6., -6., -6., -6., -6., -6., -6.])
tensor(5.5431e-05)
tensor([ 7., -7., -7., -7., -7., -7., -7., -7., -7., -7.])
tensor(7.5102e-06)
tensor([ 8., -8., -8., -8., -8., -8., -8., -8., -8., -8.])
tensor(1.0729e-06)
tensor([ 9., -9., -9., -9., -9., -9., -9., -9., -9., -9.])
tensor(1.1921e-07)
